### PR TITLE
Small fixes to cosi-install.sh

### PR DESCRIPTION
**Pull request by HeinrichHartmann**
cf. commit messages

### CODE REVIEW

**Comment by maier** [comment]
have you tested these changes on centos, ubuntu, and omnios?

**Comment by HeinrichHartmann** [comment]
No. Just locally on OSX.

**Comment by maier** [comment]
you can use the vagrant VMs in the demo subdirectory to test each of the distros we support. 

better instructions for getting the ball rolling, the [development](https://github.com/circonus-labs/circonus-one-step-install#development) section of main readme.

---

```
cd src
make package

cd ../demo
vagrant up site
```

Will create the cosi-stie package and start up a local cosi-site VM that the clients can use.

```
vagrant up <client type>
```

see the `Vagrantfile` for client types (e.g. c7 is centos7, u14 is ubuntu 14.04, etc.)

then, ssh into the client and use `--cosiurl http://cosi.circonus.com/` which will point to the local cosi-site running on the `site` VM.

**Comment by maier** [comment]
i'm seeing failures in testing on supported system types.

#centos7

```
Started Circonus One step Install on Fri Nov 11 14:58:03 UTC 2016
Initializing cosi-install
Parsing command line parameters
Verifying COSI support for OS
    Attempt RedHat(variant) detection
    Derived CentOS v7.2.1511 from 'centos-release-7-2.1511.el7.centos.2.10.x86_64'
    Looking up Linux CentOS v7.2.1511 x86_64.
    CentOS 7.2.1511 x86_64 supported!
Checking Agent state
Agent not found, installing Agent
Downloading Agent package http://updates.circonus.net/node-agent/packages/nad-omnibus-20161101T162739Z-1.el7.x86_64.rpm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9.9M  100  9.9M    0     0   768k      0  0:00:13  0:00:13 --:--:--  599k
Installing agent package /opt/circonus/cosi/cache/nad-omnibus-20161101T162739Z-1.el7.x86_64.rpm
Preparing packages...
nad-omnibus-20161101T162739Z-1.el7.x86_64
Agent POST hook found, running...
Install NAD memory usage metrics plugin
mkdir: created directory ‘nadmemory’
‘/vagrant/hooks/c7/nadmemory.js’ -> ‘/opt/circonus/etc/node-agent.d/nadmemory/nadmemory.js’
Install load.sh for CentOS 7
Restarting nad (via systemctl):                            [  OK  ]
Installing example ruleset
mkdir: created directory ‘/opt/circonus/cosi/rulesets’
‘/vagrant/hooks/c7/ruleset-load.json’ -> ‘/opt/circonus/cosi/rulesets/load.json’
NAD installation found
NAD process running PID:12481
NAD URL reachable
Agent running and responding

Retrieving COSI utilities http://cosi.circonus.com/utils
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  228k  100  228k    0     0  17.1M      0 --:--:-- --:--:-- --:--:-- 18.6M
Unpacking COSI utilities into /opt/circonus/cosi
Installing required node modules for COSI utilities
Cleaning up after node module installation
Verifying node version...
which: no node in (/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin)
Fixing cosi util shebangs...
sed: can't read : No such file or directory
```

#ubuntu14

```
Started Circonus One step Install on Fri Nov 11 15:09:11 UTC 2016
Initializing cosi-install
Parsing command line parameters
Verifying COSI support for OS
    LSB found, using '/etc/lsb-release' for OS detection.
    Looking up Linux Ubuntu v14.04 x86_64.
    Ubuntu 14.04 x86_64 supported!
Checking Agent state
Agent not found, installing Agent
Downloading Agent package http://updates.circonus.net/node-agent/packages/nad-omnibus-20161101T162739Z-1.ubuntu.14.04_amd64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11.8M  100 11.8M    0     0   767k      0  0:00:15  0:00:15 --:--:--  615k
Installing agent package /opt/circonus/cosi/cache/nad-omnibus-20161101T162739Z-1.ubuntu.14.04_amd64.deb
Selecting previously unselected package nad-omnibus.
(Reading database ... 62992 files and directories currently installed.)
Preparing to unpack .../nad-omnibus-20161101T162739Z-1.ubuntu.14.04_amd64.deb ...
Unpacking nad-omnibus (20161101T162739Z-1) ...
Setting up nad-omnibus (20161101T162739Z-1) ...
 Adding system startup for /etc/init.d/nad ...
   /etc/rc0.d/K02nad -> ../init.d/nad
   /etc/rc1.d/K02nad -> ../init.d/nad
   /etc/rc6.d/K02nad -> ../init.d/nad
   /etc/rc2.d/S98nad -> ../init.d/nad
   /etc/rc3.d/S98nad -> ../init.d/nad
   /etc/rc4.d/S98nad -> ../init.d/nad
   /etc/rc5.d/S98nad -> ../init.d/nad
 * Starting Circonus node agent daemon nad
   ...done.
Processing triggers for ureadahead (0.100.0-16) ...
NAD installation found
NAD process running PID:2181
NAD URL reachable
Agent running and responding

Retrieving COSI utilities http://cosi.circonus.com/utils
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  228k  100  228k    0     0  11.0M      0 --:--:-- --:--:-- --:--:-- 11.1M
Unpacking COSI utilities into /opt/circonus/cosi
Installing required node modules for COSI utilities
Cleaning up after node module installation
Verifying node version...
Fixing cosi util shebangs...
sed: can't read : No such file or directory
```

#omnios

```
Started Circonus One step Install on November 11, 2016 03:34:15 PM UTC
Initializing cosi-install
Parsing command line parameters
Verifying COSI support for OS
        Attempt SunOS(variant) detection
        Found /etc/release - using 'OmniOS v11 r151014'
        Looking up SunOS OmniOS vr151014 amd64.
    OmniOS r151014 amd64 supported!
Checking Agent state
Agent not found, installing Agent
 Startup: Refreshing catalog 'circonus' ... Done
 Startup: Caching catalogs ... Done
 Startup: Refreshing catalog 'circonus' ... Done
 Startup: Refreshing catalog 'omnios' ... Done
 Startup: Caching catalogs ... Done
Planning: Solver setup ... Done
Planning: Running solver ... Done
Planning: Finding local manifests ... Done
Planning: Fetching manifests: 0/3  0% complete
Planning: Fetching manifests: 3/3  100% complete
Planning: Package planning ... Done
Planning: Merging actions ... Done
Planning: Checking for conflicting actions ... Done
Planning: Consolidating action changes ... Done
Planning: Evaluating mediators ... Done
Planning: Planning completed in 10.39 seconds
           Packages to install:  3
            Services to change:  2
       Create boot environment: No
Create backup boot environment: No

Download:    0/2869 items   0.0/10.2MB  0% complete
Download: 1755/2869 items   2.2/10.2MB  21% complete (437k/s)
Download: 2847/2869 items   6.7/10.2MB  66% complete (688k/s)
Download: 2847/2869 items   9.3/10.2MB  91% complete (731k/s)
Download: Completed 10.19 MB in 16.69 seconds (622k/s)
 Actions:    1/3563 actions (Installing new actions)
 Actions: Completed 3563 actions in 3.10 seconds.
 Done
 Done
 Done
 Done
Agent POST hook found, running...
mkdir: created directory ‘/opt/circonus/etc/node-agent.d/omnios’
Disabling certain plugins
  blank output for vm
removed ‘/opt/circonus/etc/node-agent.d/sdinfo.sh’
removed ‘/opt/circonus/etc/node-agent.d/vnic.sh’
removed ‘/opt/circonus/etc/node-agent.d/zone_vfs.sh’
  detailed metrics for specific use cases
removed ‘/opt/circonus/etc/node-agent.d/aggcpu.elf’
removed ‘/opt/circonus/etc/node-agent.d/tcp.sh’
removed ‘/opt/circonus/etc/node-agent.d/udp.sh’
  replacing
removed ‘/opt/circonus/etc/node-agent.d/if.sh’
removed ‘/opt/circonus/etc/node-agent.d/vminfo.sh’

Instaling iflink.sh
‘/vagrant/hooks/omnios/iflink.sh’ -> ‘/opt/circonus/etc/node-agent.d/omnios/iflink.sh’

Instaling vm.sh
‘/vagrant/hooks/omnios/vm.sh’ -> ‘/opt/circonus/etc/node-agent.d/omnios/vm.sh’
NAD installation found
NAD process running PID:936
NAD URL reachable
Agent running and responding

Retrieving COSI utilities http://cosi-site/utils
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  228k  100  228k    0     0  8052k      0 --:--:-- --:--:-- --:--:-- 11.7M
Unpacking COSI utilities into /opt/circonus/cosi
Installing required node modules for COSI utilities
Cleaning up after node module installation
Verifying node version...
Fixing cosi util shebangs...
sed: can't read : No such file or directory
```

**Comment by HeinrichHartmann** [comment]
Thanks for testing. Apparently GNU sed does not like `-i ""`. I'll revert this change and add a comment.

**Comment by smartb-pair** [comment]
Test Kitchen (which is built on Vagrant) might be useful here as part of a CI workflow: http://kitchen.ci/

**Comment by HeinrichHartmann** [comment]
Cleaning up this PR. Not sure this is really needed.

**Pull request closed without merging**
