### PR TITLE
README: Add introduction

### PR DESCRIPTION
**Pull request by HeinrichHartmann**
Rename COSI -> C:OSI to match with use on the blog.

### CODE REVIEW

**Comment by maier** [comment]
where did the colon come from?

**Comment by HeinrichHartmann** [comment]
https://www.circonus.com/circonus-one-step-install/
https://support.circonus.com/support/solutions/articles/6000130747-c-osi-tutorial
...

**Comment by HeinrichHartmann** [comment]
Removed the ":". Any objections to merge?

**Comment by maier** [comment]
good to merge

**Pull request merged**
